---
name: dist
on: [push]

defaults:
  runs-on: ubuntu-latest
  container: robotpy/roborio-cross-ubuntu:2020.1-20.04

jobs:

  test1:
    steps:
    - uses: actions/checkout@v2
    - run: ls /

  test2:
    steps:
    - uses: actions/checkout@v2
    - run: ls /
    