---
name: dist
on: [push]

jobs:
  setup_concurrency:
    runs-on: ubuntu-latest
    outputs:
      max-parallel: ${{ steps.max-parallel.outputs.p }}
    steps:
    - name: Setup concurrency
      shell: bash
      id: max-parallel
      run: |
        if [[ "{{ github.ref_name }}" == "master" ]]; then
          echo "p=1" >> $GITHUB_OUTPUT
        else
          echo "p=1000" >> $GITHUB_OUTPUT
        fi

  build:
    runs-on: ${{ matrix.os }}
    needs: [setup_concurrency]
    strategy:
      max-parallel: ${{ needs.setup_concurrency.outputs.max-parallel }}
      matrix: 
        os: ["windows-2022", "macos-11", "ubuntu-22.04"]
        python_version:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'

    steps:
    - shell: bash
      run: sleep 5